# Site Settings
baseurl:            "" # Base URL must end WITHOUT a slash, default: ""
permalink:          /showcases/:title # Post permalink

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed
